### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by koljanich** [smolbun/Air101-LCD-ESP32-C3#1]
Hello! Write this sketch, BL to 00 pin, But screen is blank... Read that is SDA, SCK is i2C interface... (https://forum.arduino.cc/t/wiring-tft-display-to-arduino-uno/470295/3)

**Comment by smolbun** [comment]
Hi I assume you're trying to connect to the Air101-LCD without the luatos ESP32 C3 board right? Could you refer to the pinout [here](https://github.com/smolbun/Air101-LCD-ESP32-C3/blob/ed9ec80aae66b42ba5d9a26a6a18703afa9bb620/lib/TFT_eSPI/User_Setups/Setup_Air101LCD_LuatOS_ESP32C3.h#L2).

**Comment by koljanich** [comment]
Thank you for quick answer! I check out contact of pins and found problem! Thank you a lot! All work great!
